### ISSUE TITLE
support for external features file when building TTF

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontmake#549]
Do you think it would be possible to use an external features file for fontmake? This is a follow-up from #506. Glyphs builds some features automagically upon export so they don't exist in the .glyphs file itself (and, therefore, don't exist when your workflow is .glyphs -> fontmake -> UFO & designspace).

I have also filed [an issue](https://forum.glyphsapp.com/t/access-and-edit-automagically-generated-ot-features-in-the-glyphs-features-panel/11621) with Glyphs as well to see if @schriftgestalt can add support for editing those features in Glyphs proper and not have them generate automatically. That being said, I can see external features files being useful for fontmake workflows.

**Comment by anthrotype** [comment]
I'm a bit confused by the word "external", can you elaborate what you mean by that?

**Comment by anthrotype** [comment]
if you mean, using `include` statements from the UFO's features.fea, that should be supported. What error are you seeing if any?

**Comment by laerm0** [comment]
"External" as in having a`features.fea` file and then telling fontmake to ignore all features in the UFO source and use those features instead.

> if you mean, using include statements from the UFO's features.fea, that should be supported.

I'm not sure what you mean by this...

I have an error, but it's due to incomplete OT code in the UFOs I am building from (i.e. broken `m2mk` code).

**Comment by anthrotype** [comment]
ignore "include" statements (you can read more on the [Adobe FEA spec](https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#3) if you like).

So by "external" you just mean "hand-written, not auto-generated by a font compiler".
There's nothing special about a UFO containing a features.fea with some hand-coded features. I would not call that "external" (in fact, if anything it is inside the UFO directory -- if that is what you mean).

When you give it a UFO containing a "features.fea" text file, fontmake will use that to compile the features. Fontmake will also try to generate kern and mark/mkmk features automatically, but _only if they are not already present_ in the UFO's features.fea.

**Comment by laerm0** [comment]
Ahh, I see. Okay, great. I understand this now. I think this will solve my problem. As always, much appreciated. :)

**Comment by anthrotype** [comment]
you're welcome :)

**Comment by schriftgestalt** [comment]
I got the request to include GPOS in exported .ufos several time now and it is moving up the list. 

I need some info on how any why people need it.

- As @anthrotype explained, fontmake is able to generate it. 
- Why generate .ufos and then feed them to fontmake instead of feeding the .glyphs to glyphLib/fontMake?

**Comment by laerm0** [comment]
Most of the issue is the family I am working on has two axes + bracket layers. I was told there were other issues with exporting UFOs from Glyphs as well, but I think @anthrotype or @m4rc1e knows more about that.

**Comment by schriftgestalt** [comment]
I was asking what reasons you have to go the .ufo > fontMake route instead of exporting from Glyphs directly. I’m not saying you shouldn’t go that route, I just like to understand why you are doing it.

**Comment by typoman** [comment]
One reason could be a designer is working with glyphs app and another is working with RF and they want to collaborate.

**Comment by medicalwei** [comment]
Here in Debian in order to put the fonts in the main archive, we have to rebuild the source of the font.

When we rebuild the fonts, we may come to a problem that the font built from source code is different in shapes or features from the font released by the author.  SIL OFL prohibits us to use Reserved Font Name if the shape or smart code is different from the upstream build, even in the rebuild of the same source code.

I believe if Glyphs.app exports features in .ufo to let fontmake include, this can resolve (some) differences of fonts that authors export from Glyphs.app.

**Comment by schriftgestalt** [comment]
I’m looking into this right now. 
It ufo export has two options right now. 
`Convert Glyph name` (use production names)
And 
`decompose smart stuff`
What options do you need? I could imagine that one `Make production ready` option would be enough?

**Comment by schriftgestalt** [comment]
And does it need production names? Or can fontMake handle them? And what is the preferred way to store production names?

**Comment by typoman** [comment]
I think adding one option would help "Include all GPOS features". Some of the GPOS features are not saved in the UFO, like kerning, mark positioning, cursive attachment. A user can only find them in the temp folder of glyphs and include them manually.

For the production names, they are saved in the ufo font.lib `public.postscriptNames` key. You can see it in the `ufo2ft.postProcessor`.

**Comment by schriftgestalt** [comment]
I just uploaded a new (cutting edge) version that writes all GPOS (currently still with the "decompose smart stuff" option) and supports `public.postscriptNames` and `public.skipExportGlyphs`.

**Comment by BoldMonday** [comment]
That is great to hear @schriftgestalt.

Two other things that spring to mind:
1. Is the `ccmp` feature also generated automatically when Glyphs generates a binary?
2. Is collapsing of combining marks to zero width included?

**Comment by schriftgestalt** [comment]
The ccmp feature can be generated inside Glyphs. If the user had added it and set it to automatic. But that was included in the .ufo already. 

The collapsing is not done, yet. I’ll fix that.

**Comment by typoman** [comment]
I forgot to mention this, another reason to export to UFO. We have a font that it doesn't compile in Glyphs app, but it does in fontmake. It throws this error in Glyphs:

`In feature 'kern' lookup 'kern_DFLT' pair positioning rules cause an offset overflow (0x10082) to a class 2 definition table`

I already knew that overflow was solved in fontTools so I used it and it worked! fontTool for the win! Unfortunately, the client hasn't permitted to share the source; otherwise, I would have sent it to you.

**Comment by schriftgestalt** [comment]
The "Use Extension Kerning" parameter might help you.

**Comment by typoman** [comment]
Could you please point me to where it's documented? I can't find it in the instance custom parameters.

**Comment by schriftgestalt** [comment]
this is in the font parameters

**Comment by typoman** [comment]
Great, it worked!
