### ISSUE TITLE
issues with kerning, working inside illustrator and new fontforge UFO3 support

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#557]
hi
I'm using fontmake(1.10.0) to generate my new Arabic variable font from two masters that are designed inside fontforge(I'm use designspace and UFO), there are three issues:
1. kernings dosen't work correctly:
![WINWORD_DiHZcKN4y1](https://user-images.githubusercontent.com/25493297/58940225-31ac6c00-878e-11e9-9d75-1b53607dd69a.png)
 after i check font again inside fontforge(fontforge parsing vf as a multimater font by ignores var tables) i realized it might work by deleting first pos values in feature.plist file(fontforge doesn't generate Kerning.plist for UFO , all Kernings are placed as a GPOS lookup table inside feature.plist file):
changing `pos \uniFEFB <-122 0 -122 0> \uni062C  <-122 0 -122 0>;`
to `pos \uniFEFB \uni062C  <-122 0 -122 0>;`
and yes! it's working fine but mark positions movements have been disabled:
before:
![Zo2HVrOXal](https://user-images.githubusercontent.com/25493297/58940677-59500400-878f-11e9-9735-5b42b545a2a4.gif)
after:
![5YhwOsojkC](https://user-images.githubusercontent.com/25493297/58940687-60771200-878f-11e9-9ac7-ced49c26200e.gif)
2. new fontforge supports ufo3 format but when i generate vf, fontmake shows me an error like this: "layercontents.plist is missing, this file is required". fontforge 2017 version dosen't generate this file too, but fontmake works well without error.
3. font works inside the web (i tested in chrome) but letters typed seperately in illustrator.(init, medi and fina not works,) how can i fix it? if it's an illustrator or other adobe products bug, how markazi-text or other arabic fonts works?

**Comment by m4rc1e** [comment]
It sounds like you've inspected the generated ttfs/otfs in fontforge? if you have, this won't work. Font editors can open these binaries but they cannot accurately decompile the fonts. You can use [OT Master Lite](https://www.fontmaster.nl/index.php/otmaster/) to properly inspect a font binary. 

1. Check the kerning in OT Master. It looks like you may be attempting to test the kerning in Illustrator.
3. What version of Illustrator are you using? It has been a while since I've used it but I remember non-Latin support was rather lacking. You will need the [MENA editions of Adobe products](https://helpx.adobe.com/uk/indesign/kb/access-install-hebrew-arabic-indesign-illustrator-CC.html) to make it work correctly. I believe Adobe are going to use harfbuzz in the future which should solve this issue.

It would help if you could upload the .ufo here.

**Comment by m4rc1e** [comment]
Here's the link to download OT Master Light https://www.fontmaster.nl/index.php/test-demo/. It's free.

**Comment by aminabedi68** [comment]
> It sounds like you've inspected the generated ttfs/otfs in fontforge? if you have, this won't work. Font editors can open these binaries but they cannot accurately decompile the fonts.
yes. i khow. i just check the kernings of one of the masters for changing feature.plist in exported UFO. it's not about Fontforge(both masters work fine in all GPOS/GSUB features), its about how fontmake handle the kernings of fontforge in feature.plist file.

> You can use OT Master Lite to properly inspect a font binary.
thank you. i just install it, all kernings seem to work but this is what happened to my font:
![WINWORD_7WYVuVxjPU](https://user-images.githubusercontent.com/25493297/58963612-bfa24a00-87c2-11e9-99d1-51890f1ae260.png)
so i can't test correctness of kernings by kerning pairs.

> It looks like you may be attempting to test the kerning in Illustrator.
No, i tested inside chrome(two above gifs). this is illustrators output:
![Cg9aiW80U7](https://user-images.githubusercontent.com/25493297/58965748-54f30d80-87c6-11e9-9b39-9b615b664554.gif)
 

> What version of Illustrator are you using? It has been a while since I've used it but I remember non-Latin support was rather lacking. You will need the MENA editions of Adobe products to make it work correctly.
it's 2018. yeah, it always has some problems with Arabic but works in official version without need to any editor/extension/plug-in...

> I believe Adobe are going to use harfbuzz in the future which should solve this issue.
good news :)

> It would help if you could upload the .ufo here.
i cant do this, whole typeface is a commercial project, I'm sorry.

**Comment by anthrotype** [comment]
I am not familiar with fontforge's UFO support but I'll do by betst to understand what the issue is.

yes, layercontents.plist is a required file (even if there is only the default layer and no additional ones) in UFO3 format. You should alert the FontForge's developers about that.

You probably mean "features.fea", when you talk about "feature.plist", is that right?

> changing
>    pos \uniFEFB <-122 0 -122 0> \uni062C <-122 0 -122 0>;
> to
>    pos \uniFEFB \uni062C <-122 0 -122 0>;
> and yes! it's working fine

Note that the two are not equivalent to each other. The first `pos` rule is changing the xPlacement and xAdvance of _both_ glyphs, whereas the second `pos` rule is changing the xPlacement/xAdvance only of the first glyph (the first in 'logical' sense, i.e. "uniFEFB").
In fact the second notation is a short-hand for 

```
position <glyph|glyphclass> <valuerecord format A> <glyph|glyphclass> <NULL>;
```

see https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#6b-gpos-lookuptype-2-pair-adjustment-positioning

I think fontmake (via fontTools.feaLib which is the library that compiles the OTL features) is doing what it's been told by fontforge. Could there be a possibility that

1) you specified the features incorrectly in fontforge;
2) fontforge is exporting them incorrectly to UFO features.fea.

**Comment by anthrotype** [comment]
> but mark positions movements have been disabled

this is probably a different issue. Can you elaborate?

**Comment by aminabedi68** [comment]
> I am not familiar with fontforge's UFO support but I'll do by best to understand what the issue is.

i understand, thank you kindly.

> yes, layercontents.plist is a required file (even if there is only the default layer and no additional ones) in UFO3 format. You should alert the FontForge's developers about that.

i will aware them later. until then i have to write it manually. I'm just wanted to be sure it's not a bug.

> You probably mean "features.fea", when you talk about "feature.plist", is that right?

> changing

    pos \uniFEFB <-122 0 -122 0> \uni062C <-122 0 -122 0>;
    to
    pos \uniFEFB \uni062C <-122 0 -122 0>;
    and yes! it's working fine

yes, stupid me, you right, i meant feature.fea 

> Note that the two are not equivalent to each other. The first pos rule is changing the xPlacement and xAdvance of both glyphs, whereas the second pos rule is changing the xPlacement/xAdvance only of the first glyph (the first in 'logical' sense, i.e. "uniFEFB").
In fact the second notation is a short-hand for

position <glyph|glyphclass> <valuerecord format A> <glyph|glyphclass> <NULL>;

see https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#6b-gpos-lookuptype-2-pair-adjustment-positioning

i'm not expert enough, going to learn it, thank you. my change was an amateur test. but how it's working correct?

> I think fontmake (via fontTools.feaLib which is the library that compiles the OTL features) is doing what it's been told by fontforge. Could there be a possibility that
   1- you specified the features incorrectly in fontforge;
    2-fontforge is exporting them incorrectly to UFO features.fea.

i'm not sure but as i say all feauturs of exported masters(individual as an ordinary opentype font) work in Adobe/Microsoft/web browsers/all opensource programs that are using harfbuzz ... but an Arabic font with calt, rtl,kernings...you know it's a trouble, so i never be sure about that. about fontforge i don't know but really hop to be not.

**Comment by aminabedi68** [comment]
> this is probably a different issue. Can you elaborate?

how can i help?

**Comment by anthrotype** [comment]
> how can i help?

by providing more details or examples.

**Comment by behdad** [comment]
Nice font.  Are you planning to Open Source that? :)

**Comment by aminabedi68** [comment]
I opened an <a href = "https://github.com/fontforge/fontforge/issues/3726#issuecomment-499656047">issue</a> in fontforge page for "layercontents.plist" and about mark positions, I will collect information and send you.

**Comment by aminabedi68** [comment]
thank you @behdad :)
i love opensource but no, this is a commercial font.

**Comment by aminabedi68** [comment]
- about mark position interpolation, it's my fault, beacuse after i change kerning codes on feature file, i replaced another feature files with it, so ...
- about kerning i talked to @khaledhosny and he opened an issue for fontforge here:
https://github.com/fontforge/fontforge/pull/3732
- illustrator still not working but i think it can't understood or solve simply, so i close this issue. thank you all.
