### ISSUE TITLE
Iogonek has negative width when generating Josefin Sans

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontmake#600]
Whilst generating Josefin Sans, we noticed that the Iogonek is negative width.

<img width="397" alt="Screenshot 2019-11-19 at 11 51 14" src="https://user-images.githubusercontent.com/7525512/69144623-96048300-0ac3-11ea-83d3-69ab30c10656.png">

The glyph is constructed from a component for the base glyph and an outline for the gonek.

<img width="223" alt="Screenshot 2019-11-19 at 11 56 56" src="https://user-images.githubusercontent.com/7525512/69144680-b59bab80-0ac3-11ea-9c0d-87b929fe8e81.png">

The component is decomposed when the font is genned.

hb-shape reports that the Iogonek has negative width:

```
[O=0+865|O=1+865|Iogonek=2@-456,0+0|O=3+865|O=4+865]
```

Here's a minimal testcase [Iogonek-testcase.zip](https://github.com/googlefonts/fontmake/files/3863597/Iogonek-testcase.zip)

Sorry for these tech support questions and if it's just dodgy design work which is causing this.

cc @pichotta @djrrb

**Comment by m4rc1e** [comment]
Just had a quick chat with Cosimo. It appears to be a GDEF issue.

```
379       <ClassDef glyph="I" class="1"/>
380       <ClassDef glyph="Iogonek" class="3"/>
381       <ClassDef glyph="O" class="1"/>
```

This is happening because we have an anchor in the glyph which has an "_"

<img width="220" alt="Screenshot 2019-11-19 at 12 38 55" src="https://user-images.githubusercontent.com/7525512/69147439-d666ff80-0ac9-11ea-84c7-8a9df3e82133.png">

**Comment by anthrotype** [comment]
if you want to have full control on what glyphs are classified as base/marks/ligatures I suggest you explicitly define a GDEF table in your UFO's features.fea. So that ufo2ft will not guess but use those classes.
If you converted the project from glyphs and used glyphs2ufo make sure you pass --generate-GDEF option, so a GDEF table is exported in UFO's features.fea based on GlyphData.xml. If you generate the UFOs with fontmake that option is on by default.
