### ISSUE TITLE
referenced glyphs replacing issue with conditional rules

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#659]
hi
i'm working with fontforge, so i'm not sure it's a fontforge UFO exporting issue or beacause of fontmake, so the issue as i say <a href="https://github.com/googlefonts/fontmake/issues/655" target="_blank">here</a> is that when we replace a glyph with another glyph using conditional rules(defined inside disignspace file) everything is OK but it's not working for any refrenced copy of that glyph inside the other glyphs.

**Comment by twardoch** [comment]
A “referenced copy” is a component. DesignSpace rules produce FeatureVariation — the ability to turn on features under certain axis conditions. If the features are GSUB (like rvrn), they just replace some glyphs with other glyphs. GSUB features don’t do anything with components. Components are used once glyphs have been laid out, when they are being rendered.

Typically in a scenario like this, you’d decompose the encoded glyphs into stroke glyphs and dot glyphs in GSUB, and use GPOS to position the dots. Since the dots are separate glyphs then, you can easily substitute them with a feature like ss01, and use the same lookups in a feature that uses FeatureVariations. This can be rvrn or another feature.

**Comment by madig** [comment]
What you're seeing is intentional. Switching one glyph will leave all glyphs referencing it as they are. You must switch all glyphs you want to switch explicitly.

Try that or what Adam suggest.

**Comment by aminabedi68** [comment]
thank you @twardoch , i read you comment over than 20 times, it's a bit complicated for me, if i have a tiny prototype then i can expand it for my work, or any font implemented with this method. thank you again.
yes @madig ! i know what you mean, alternates for all dot glyphs with other dot style glyphs, then i have to put all kernings between alternates, and if i want to have more dot styles or if i need to expand the font to have more glyphs...this is not a good idea!
for this case let's assume we have 2 masters with only defference in dot styles, which is used as reference copies in all glyphs, if we have a related axis and don't want to choose any points between, we need to change axis "step" size (like css slider step size), or map values(?) into very small values... i don't know, maybe it works... what you think?

**Comment by twardoch** [comment]
If you really want a “discrete” slider, FeatureVariations is the right solution. And you can get them via the Designspace rules. In the end, it's simply a GSUB substitution in a feature like rvrn. 

If you want a slider with only two discrete states, I wonder what's the reason not to use the traditional features like ss01. I'm just curious.

There is no problem to do what you intend to do. Since it's GSUB features, you need glyphs. If you use many precomposed glyphs, you need many more glyphs, and larger classes. 

To avoid that, use fewer precomposed glyphs. You can put the decomposition into "ccmp" and to really make sure that apps do it, your can also put it as a first lookup of "rvrn". But you'll need to work with the GSUB TTX syntax a bit, I think.  

One decomposed, the glyphs will be a stream of strokes and dots (or dot groups). Swap them with "rvrn" conditional subsitutions (rules) or the traditional "ss01" feature. Then, position any dots via mark positioning. All major font editors can build a "mark" feature from anchors.

**Comment by aminabedi68** [comment]
wow, i get it, it's perfect 👌 thank you @twardoch
