### ISSUE TITLE
Panose values are ignored

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontmake#688]
I am mastering a monospace font, PANOSE and isfixedpitch flad are set correctly in the source file, although I had fails for monospace metadata. I corrected it with a gftools script, although fontmake should take panose values into account during generation, right ?

**Comment by m4rc1e** [comment]
Further info:

The .glyphs file, https://gitlab.com/RosaWagner/syne-typeface/-/blob/master/sources/SyneMono.glyphs

The command used `fontmake -g SyneMono.glyphs -o ttf -i`


Running `glyphs2ufo` on the source does convert the panose customParameter correctly.

**Comment by anthrotype** [comment]
I believe the panose custom parameter is supposed to be set on the instances, as you're building a static instance. Whereas your source has it on the font. Does Glyphs.app allow to add panose custom parameter on the font as well? Does that get inherited by all the instances (that do not override it)?

I see that openTypeOS2Panose attribute is correctly set in the master_ufo/SyneMono-Mono.ufo/fontinfo.plist, but it is missing from the instance_ufo/SyneMono-Regular.ufo/fontinfo.plist, leading to the missing panose in the generated TTF.

Nikolaus @madig deliberately excluded openTypeOS2Panose attribute from the fontinfo attributes that are copied from the default master to all the instances, because the assumption is that this parameter should be set differently on each instance:
https://github.com/googlefonts/fontmake/blob/f07b1932768efdee8f15a4a9179d1c2d181ceb8a/Lib/fontmake/instantiator.py#L78-L148

You should be able to fix this problem by setting your panose on the instances rather than on the global font. But i'd like to know what Glyphs.app is doing with that, whether the parameter appears "greyed out" in the Font panel or not, and whether it is applied to instances that don't have explicit panose.

**Comment by RosaWagner** [comment]
It works indeed with the panose values in the instance custom parameters.
