### ISSUE TITLE
Why isn’t --interpolate-binary-layout the default

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontmake#694]
I was surprized to find out that `-i` option does not interpolate OTL tables and that one needs to additionally pass `--interpolate-binary-layout`, which has the cryptic and misleading help string:

```
  --interpolate-binary-layout [MASTER_DIR]
                        Interpolate layout tables from compiled master binaries. Requires Glyphs or MutatorMath source.
```

(what is `MASTER_DIR` is for? and I have no idea what is a “MutatorMath source”, I’m using UFOs with a DesignSpace file)

Any reason this is not done by default, why would one not want to interpolate OTL tables?

**Comment by punchcutter** [comment]
`-i` _does_ interpolate OTL tables from source. From what I remember one of the main reasons `--interpolate-binary-layout` was included was because mtiLib was never written in a way to interpolate from those sources so varLib was set up to build the binary TTFs using MTI source files and then `--interpolate-binary-layout` was run to interpolate that. For anything else the interpolation is done on the source files (Glyphs or UFO).

**Comment by khaledhosny** [comment]
I guess you mean it interpolates UFO/Glyphs kerning and anchors (I’m not using these), but what about positioning data in the feature code, that does not seem to be interpolated.

**Comment by khaledhosny** [comment]
(in general, I find compiling OTL tables then interpolating them with varLib to be superior, but UFO and Glyphs files are poor at representing positioning data that does not fit in their rather limited view of kerning/anchoring.)
