### ISSUE TITLE
From Glyphs source: why does 'i acutecomb' become 'iacute', but 'j acutecomb' is just 'jdotless acutecomb'?

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontmake#758]
I am working on a font with a GlyphsApp (v2)  source, building with FontMake.

I am trying to make sure the Dutch íj́ will work properly, and it seems that a reliable strategy (at least for fonts that don’t have a specific `ijacute` ligature) would be to simply sub `i acutecomb` for `iacute` and then sub `j acutecomb` for `jacute`. It appears that, for example, this is what SF Pro does:

![image](https://user-images.githubusercontent.com/45946693/113633579-34eb3a00-963b-11eb-962e-738e66af8b7a.png)

The Glyphs source:
- Includes `jdotless` (Unicode `0237`), `acutecomb` (Unicode `0301`), and `jacute` (a precomposed character for which no Unicode value exists)
- Includes the `top` anchor in `jdotless` and the `_top` anchor in `acutecomb`,  to combine them where desired

However, these do not combine into `jacute` when typed, but rather just a `jdotless` and `acutecomb`.

Is this because `jacute` doesn’t have a Unicode value? Is something special needed to make this happen? (E.g. do I need to set up classes or other `ccmp` feature code myself)? I also need to set up `.case` versions of combining accents ... will I need to do something special for these, or would FontMake’s auto feature generation cover these if I name them / classify them in a certain way?

I realize that a lot of folks write their own `mark` and `mkmk` features / feature generators, and I’m partly trying to understand at what point I should be doing that, vs what I can do that will work automatically.

Thank you for any insights!

**Comment by RosaWagner** [comment]
If you update and compile your features in glyphs, it should look like this:

![Capture d’écran 2021-04-06 à 18 35 04](https://user-images.githubusercontent.com/12222436/113746671-de4b3200-9706-11eb-8969-c1356f714336.png)

But since this is a localized feature, you need to set the language in Dutch (like in Indesign) so the substitution can work.

**Comment by moyogo** [comment]
Fontmake auto feature generation only adds kerning and mark positioning.
It sounds like you have a `sub j by jdotless` when followed by a mark above that happens before the `sub j acutecomb by jacute`.

For the mark feature writer to generate code, it either adds mark feature code if no mark feature block is already present or, with the latest version of fontmake, will also add mark feature code if the mark feature block starts or ends with the comment "# Automatic Code" (or also "# Automatic Code Start" or "# Automatic Code End" like Glyphs.app 2) before or after that block. Alternatively there's also a way to append the mark feature code, but using the comment is more flexible.

**Comment by arrowtype** [comment]
Thank you both for taking time to respond helpfully! I really appreciate it. This helped me understand the bigger picture, and I think I’ve figured things out now.

> If you update and compile your features in glyphs, it should look like this

Thank you, @RosaWagner! I should have added a bit more detail – I think that code is what is suggested by the tutorial from GlyphsApp, but I am not sure whether it is the actual best solution (it definitely could be, but I’m trying to verify that). I have heard that Dutch keyboards are encoded to input `j acutecomb`, and if I just try typing íj́ on a Mac, I type `option+e, i, option+e, j`. This works with SF Pro, but doesn’t work with my current font, if built with that `locl` feature.

> since this is a localized feature, you need to set the language in Dutch (like in Indesign) so the substitution can work.

Thanks for pointing this out! That definitely confused me for awhile, and needs to be included in anything on this topic.

> It sounds like you have a `sub j by jdotless` when followed by a mark above that happens before the `sub j acutecomb by jacute`.

@moyogo Ahhh yes, this was a very good guess, and it helped point to a solution. Glyphs did help me generate some `ccmp` code that was basically the first part. And then, I suppose maybe FontMake generated the second part? I do see that if I specifically add `sub jdotless acutecomb by jacute` in the `locl` feature, it starts to work as I expect it to. Though, maybe I should put this in a feature that doesn’t need language activation, as I don’t see this causing problems for languages _outside of_ Dutch. I don’t have to handle a 

> with the latest version of fontmake, will also add mark feature code if the mark feature block starts or ends with the comment "# Automatic Code" (or also "# Automatic Code Start" or "# Automatic Code End" like Glyphs.app 2) before or after that block.

Oh wow, cool! That will probably come in handy sooner or later.

---

For now, I’ve just added `sub jdotless acutecomb by jacute` and `sub J acutecomb by Jacute` in a new lookup at the end of the `ccmp` feature. Then, I’m using the `locl` feature `language NLD` lookup  for just the `ij` and `IJ` ligatures (the font doesn’t have `ijacute` and `IJacute` ligatures, though perhaps it should...)

So, I think I’m understanding this better now. Thanks again!

**Comment by BoldMonday** [comment]
Please don't presume that `i` + `j` is always meant to be the Dutch digraph `ij`. The combination can also occur in names such as **Fiji**.

Therefore don’t assume that `iacute` should always be followed by `jacute` in that case too.
In Dutch it would be possible to write something like: _“Nee, het is niet Fúji maar Fíji!”_

I don’t think fonts should make decisions that are better to be handled by a text engine.
Fonts that try to be too smart are in the end just... not so smart.

**Comment by twardoch** [comment]
Yes, OpenType code that tries to automatically solve text encoding issues is problematic. It encourages bad encoding, because the font fixes it »in post«. 

The `locl` workaround for Romanian is a very isolated case that addresses an ancient bad decision of Unicode. 

The `locl` stuff for Turkish is made to _prevent_ automatic ligation. That’s OK — it‘s the »better safe than sorry« approach. Preventing overzealous substitutions (like fi ligation that blurs the visual distinction between dotted and dotless i) is a good thing to put into OT logic. 

But actively making some additional substitutions that visually change the nature of the text is something I’d discourage, except in limited-release fonts.

**Comment by arrowtype** [comment]
@BoldMonday  okay, my mistake – thank you for the correction! I assume your recommended approach can be found in IBM Plex?

**Comment by arrowtype** [comment]
Or wait ... @BoldMonday, do you simply think that there should be no `locl` code to handle the `ij` and `ijacute`?

It looks like Plex leaves it out entirely.

https://github.com/IBM/plex/blob/270ee7ade3f34e5ce26195769e67c68c71847ad2/IBM-Plex-Sans/sources/masters/IBM%20Plex%20Sans-Regular.ufo/features.fea#L104-L113

What if a font has a specific ligature for these glyphs? Should they be activated at all in `locl`, or should they be in `dlig` or similar? Do Dutch users have a way to type these glyphs when they want them?

**Comment by BoldMonday** [comment]
@arrowtype Indeed I think the `locl` feature is not a good place for these matters because font users have absolutely no control over it because it is supposed to be on by default.
But let's seperate two issues here: the case of the Dutch `ij` digraph and the case of `j` with `acute`.

**Dutch ij digraph**
Type designers can choose to include U+0132 (`IJ`) and U+0133 (`ij`) in their fonts. However Dutch keyboards do not offer any way to input these characters. Dutch people just type `i` and `j` seperately and as far as I know that is also how these characters are stored in text. At least I don't know of any text engine doing any conversion.
We include U+0132 and U+0133 by default in all our fonts just for the sake of completeness and compatibility. Sometimes we design these digraphs specifically as a ligated shape but often just as simple i+j compound glyphs.

Depending on the design of the typeface and target audience we decide whether and how to make ligated shapes accessible. In case of certain display typefaces targeted to primarily a Dutch audience (e.g. custom fonts) we might put these digraphs in the `liga` feature without any language specific rules. (This is the brute force approach not recommended for international audiences.)
In other cases we might put these digraphs in the `dlig` feature (again without any language specific rules). In this scenario font users who are familiar with OpenType features can easily switch on/off the ligated shapes if they want to.
And sometimes we decide not to put the ligated shapes in any feature. Then the user can still access them by inserting them as unicode characters by using a glyph palette. This is what we decided to do for Plex. Here it is more of an Easter egg (_een Paasij!_) for a select audience.

**j with acute**
Sometime ago we decided that the most future-proof way of making this combination available to everyone (not only Dutch people) is by using the `mark` feature. Font users need to input `j` with `combining acute` and then the `mark` and `ccmp` features will take care of the proper appearance of this glyph. This way ensures that the underlying Unicode text is therefore completely portable.
