### ISSUE TITLE
Error with ttf autohint

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontmake#857]
While trying to debug another font that doesn't build, I try to build once that I know usually work, but build stopped with this error.

```
fontmake.errors.TTFAError: In 'JetBrainsMono.glyphs' -> 'master_ufo/JetBrainsMono.designspace' -> '../../../../../../var/folders/vl/n4rcymz90tq0jb2913m97fs80000gn/T/tmp9oj2j59b.ttf': ttfautohint failed with error code {str(self.exitcode)}
```

**Comment by anthrotype** [comment]
that it doesn't actually print the exitcode is a bug, which I just fixed on main here => https://github.com/googlefonts/fontmake/commit/c970d904381356aec26eab6ae523a698895bc0b3

If you retry building off fontamake latest main branch, it should at least give you the exit code, which may aid debugging.

Can you also try running `ttfautohint` command (or `python -m ttfautohint` is using ttfautohint-py) manually instead of through fontmake and confirm it throws the same error?

**Comment by RosaWagner** [comment]
The font builds using the last main branch

**Comment by RosaWagner** [comment]
Using builder with last main branch of fontmake:
`ttfautohint failed with error code -11`

Using `fontmake -g font.glyphs -o ttf`
I get ttf files, but there are the 3 masters, not the actual 8 instances, and no ttfautohint applied

running `python -m ttfautohint` on the ttf files
`Segmentation fault: 11`

**Comment by anthrotype** [comment]
Thanks. Ok so this is probably https://github.com/fonttools/ttfautohint-py/issues/14

**Comment by anthrotype** [comment]
As a workaround, try `pip uninstall ttfautohint-py` and the `brew install ttfautohint`

**Comment by simoncozens** [comment]
This should now be fixed, with the latest ttfautohint-py.

**Comment by sursly** [comment]
Commenting to say that I updated it as @simoncozens suggested and my error is gone 👍
